# Generated by Django 4.2.15 on 2024-08-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('tutor_name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('excerpt', models.TextField(blank=True)),
                ('date', models.TextField(blank=True)),
                ('time', models.TextField(blank=True)),
            ],
        ),
    ]
