# Generated by Django 4.2.15 on 2024-08-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='date',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='time',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='tutorial_date',
            field=models.DateTimeField(default='2024-08-17 00:10:00'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='excerpt',
            field=models.TextField(),
        ),
    ]
