# Generated by Django 4.2.15 on 2024-08-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0003_remove_tutorial_tutorial_date_tutorialdate_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='slug',
            field=models.SlugField(default=1, max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutor_name',
            field=models.CharField(max_length=30),
        ),
    ]
