# Generated by Django 4.2.15 on 2024-08-18 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0004_tutorial_slug_alter_tutorial_tutor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorialdate',
            name='user',
        ),
    ]
