# Generated by Django 4.2.15 on 2024-09-20 06:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0005_remove_tutorialdate_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
