# Generated by Django 4.2.15 on 2024-09-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0006_tutorial_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='alt_text',
            field=models.CharField(default='alt text', max_length=150, verbose_name='alt text'),
            preserve_default=False,
        ),
    ]
